const MAX_LAST_WATCHED_CONTENT_LIMIT = 5;
const MIN_PASSWORD_LENGTH = 4;
const MAX_PASSWORD_LENGTH = 16;
const ENABLE_18_AGE_LIMIT_CHECK = false;
const ADD_IMDB_RATING_TO_CONTENT = true;
const MAX_PROFILES_LIMIT = 4;
module.exports = 
{
    MAX_LAST_WATCHED_CONTENT_LIMIT,
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    ENABLE_18_AGE_LIMIT_CHECK,
    ADD_IMDB_RATING_TO_CONTENT,
    MAX_PROFILES_LIMIT
};