/* eslint-disable no-unused-vars */
const { User, UserProfile, Media } = require('../entities.js');
const StorageContract = require('./storage-contract.js');
/**
 * @typedef {Object} StorageResponse
 * @property {boolean} success - Operation status
 * @property {string} [message] - Message describing the operation result
 * @property {any} [data] - Returned data (User, Array of Media, etc.)
 */

/**
 * Abstract Base Class defining the Data Access Layer.
 */
class MemoryStorage extends StorageContract
{
    constructor()
    {
        super();
        this.users = {};//key: userId, value: User
        this.AvailableUserId = 0;
        this.email2userId = {};//key: email, value: UserId
        this.phone2userId = {};//key: phone, value: UserId
        this.media = {};//key: mediaId, value: Media

    }

    // ==========================================
    // User & Auth Management
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllUsers() { return { success: true, data: Object.values(this.users) }; }

    /** @param {string} email @returns {Promise<StorageResponse>} */
    async getUserByEmail(email) 
    { 
        const userId = this.email2userId[email];
        if (!userId) { return { success: false, message: "User not found" }; }
        return { success: true, data: this.users[userId].clone()}; 
    }

    /** @param {string} phone @returns {Promise<StorageResponse>} */
    async getUserByPhone(phone) 
    { 
        const userId = this.phone2userId[phone];
        if (!userId) { return { success: false, message: "User not found" }; }
        return { success: true, data: this.users[userId].clone()}; 
    }

    /** @param {User} user object instance (id need to be undefined in order to be generated by the storage layer) @returns {Promise<StorageResponse>} */
    async registerUser(user) 
    { 
        if (user.id !== undefined) { return { success: false, message: "User id must be undefined in order to be generated by the storage layer" }; }
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (this.email2userId[user.email]) { return { success: false, message: "Email already exists" }; }
        if (this.phone2userId[user.phone]) { return { success: false, message: "Phone already exists" }; }
        user.id = this.AvailableUserId;
        this.AvailableUserId += 1;
        this.users[user.id] = user.clone();
        this.email2userId[user.email] = user.id;
        this.phone2userId[user.phone] = user.id;
        return { success: true, data: user }; 
    }

    /** @param {User} user @returns {Promise<StorageResponse>} */
    async updateUser(user)
    {
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (user.id === undefined || Number.isNaN(user.id) || user.id < 0) { return { success: false, message: "User id must be defined and positive" }; }
        
        const existingUser = this.users[user.id];
        if (!existingUser) { return { success: false, message: "User not found" }; }

        if (this.email2userId[user.email] && this.email2userId[user.email] !== user.id)
        { 
            return { success: false, message: "Email already exists" }; 
        }
        if (this.phone2userId[user.phone] && this.phone2userId[user.phone] !== user.id)
        { 
            return { success: false, message: "Phone already exists" }; 
        }
        
        delete this.email2userId[existingUser.email];
        delete this.phone2userId[existingUser.phone];

        this.users[user.id] = user.clone();
        this.email2userId[user.email] = user.id;
        this.phone2userId[user.phone] = user.id;

        return { success: true, data: user };
    }
    // ==========================================
    // Profile Management
    // ==========================================

    /** @param {number} userId @returns {Promise<StorageResponse>} */
    async getUserProfiles(userId)
    {
        if (typeof userId !== 'number' || Number.isNaN(userId)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userId];
        if (!user) { return { success: false, message: "User not found" }; }
        return { success: true, data: user.profiles.map(p => p.toJSON()) };
    }

    /** @param {number} userId @param {UserProfile[]} profiles @returns {Promise<StorageResponse>} */
    async saveUserProfiles(userId, profiles)
    {
        if (typeof userId !== 'number' || Number.isNaN(userId)) { return { success: false, message: "User id must be a number" }; }
        if (!Array.isArray(profiles)) { return { success: false, message: "Profiles must be an array" }; }
        if (profiles.length === 0) { return { success: false, message: "Profiles array must not be empty" }; }
        if (profiles.some(p => !(p instanceof UserProfile))) { return { success: false, message: "Profiles array must contain only UserProfile instances" }; }
        const user = this.users[userId];
        if (!user) { return { success: false, message: "User not found" }; }
        user.profiles = profiles.map(p => p.clone());
        return { success: true, message: "Profiles saved successfully" };
    }

    // ==========================================
    // Media & Interaction
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllMedia() { throw new Error("Method not implemented."); }

    /** @param {number} mediaId @returns {Promise<StorageResponse>} */
    async getMediaById(mediaId) { throw new Error("Method not implemented."); }

    /** 
     * @param {number} userId 
     * @param {number} profileId 
     * @param {number} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async toggleMediaLike(userId, profileId, mediaId) { throw new Error("Method not implemented."); }

    /** 
     * @param {number} userId 
     * @param {number} profileId 
     * @param {number} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async addMediaToWatchHistory(userId, profileId, mediaId) { throw new Error("Method not implemented."); }
}

module.exports = MemoryStorage;