/* eslint-disable no-unused-vars */
const { User, UserProfile, Media } = require('../entities.js');
const StorageContract = require('./storage-contract.js');
const Constants = require('../constances.js');
/**
 * @typedef {Object} StorageResponse
 * @property {boolean} success - Operation status
 * @property {string} [message] - Message describing the operation result
 * @property {any} [data] - Returned data (User, Array of Media, etc.)
 */

/**
 * Abstract Base Class defining the Data Access Layer.
 */
class MemoryStorage extends StorageContract
{
    constructor()
    {
        super();
        this.users = {};//key: userId, value: User
        this.AvailableUserId = 0;
        this.email2userId = {};//key: email, value: UserId
        this.phone2userId = {};//key: phone, value: UserId
        this.media = {};//key: mediaId, value: Media

    }

    // ==========================================
    // User & Auth Management
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllUsers() { return { success: true, data: Object.values(this.users).map(u => u.toJSON()) }; }

    /** @param {string} email @returns {Promise<StorageResponse>} */
    async getUserByEmail(email) 
    { 
        const userId = this.email2userId[email];
        if (!userId) { return { success: false, message: "User not found" }; }
        return { success: true, data: this.users[userId].toJSON()}; 
    }

    /** @param {string} phone @returns {Promise<StorageResponse>} */
    async getUserByPhone(phone) 
    { 
        const userId = this.phone2userId[phone];
        if (!userId) { return { success: false, message: "User not found" }; }
        return { success: true, data: this.users[userId].toJSON()}; 
    }

    /** @param {User} user object instance (id need to be undefined in order to be generated by the storage layer) @returns {Promise<StorageResponse>} */
    async registerUser(user) 
    { 
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (user.id !== undefined) { return { success: false, message: "User id must be undefined in order to be generated by the storage layer" }; }
        if (this.email2userId[user.email]) { return { success: false, message: "Email already exists" }; }
        if (this.phone2userId[user.phone]) { return { success: false, message: "Phone already exists" }; }
        user.id = this.AvailableUserId;
        this.AvailableUserId += 1;
        this.users[user.id] = user.clone();
        this.email2userId[user.email] = user.id;
        this.phone2userId[user.phone] = user.id;
        return { success: true, data: user.toJSON()}; 
    }

    /** @param {User} user @returns {Promise<StorageResponse>} */
    async updateUser(user)
    {
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (user.id === undefined || Number.isNaN(user.id) || user.id < 0) { return { success: false, message: "User id must be defined and positive" }; }
        
        const existingUser = this.users[user.id];
        if (!existingUser) { return { success: false, message: "User not found" }; }

        if (this.email2userId[user.email] && this.email2userId[user.email] !== user.id)
        { 
            return { success: false, message: "Email already exists" }; 
        }
        if (this.phone2userId[user.phone] && this.phone2userId[user.phone] !== user.id)
        { 
            return { success: false, message: "Phone already exists" }; 
        }
        
        delete this.email2userId[existingUser.email];
        delete this.phone2userId[existingUser.phone];

        this.users[user.id] = user.clone();
        this.email2userId[user.email] = user.id;
        this.phone2userId[user.phone] = user.id;

        return { success: true, data: user.toJSON()};
    }
    // ==========================================
    // Profile Management
    // ==========================================

    /** @param {string} userId @returns {Promise<StorageResponse>} */
    async getUserProfiles(userId)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        return { success: true, data: user.profiles.map(p => p.toJSON()) };
    }

    /** @param {string} userId @param {UserProfile[]} profiles @returns {Promise<StorageResponse>} */
    async saveUserProfiles(userId, profiles)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        if (!Array.isArray(profiles)) { return { success: false, message: "Profiles must be an array" }; }
        if (profiles.length === 0) { return { success: false, message: "Profiles array must not be empty" }; }
        if (profiles.some(p => !(p instanceof UserProfile))) { return { success: false, message: "Profiles array must contain only UserProfile instances" }; }
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        user.profiles = profiles.map(p => p.clone());
        return { success: true, message: "Profiles saved successfully" };
    }

    // ==========================================
    // Media & Interaction
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllMedia()
    {
        return { success: true, data: Object.values(this.media).map(m => m.toJSON()) };
    }

    /** @param {number} mediaId @returns {Promise<StorageResponse>} */
    async getMediaById(mediaId)
    {
        const media = this.media[mediaId];
        if (!media) { return { success: false, message: "Media not found" }; }
        return { success: true, data: media.toJSON() };
    }

    /** 
     * @param {string} userId 
     * @param {string} profileId 
     * @param {string} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async toggleMediaLike(userId, profileId, mediaId) 
    {
        const mediaIdNumber = Number(mediaId);
        if (Number.isNaN(mediaIdNumber)) { return { success: false, message: "Media id must be a number" }; }
        const media = this.media[mediaIdNumber];
        if (!media) { return { success: false, message: "Media not found" }; }
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        const profileIdNumber = Number(profileId);
        if (Number.isNaN(profileIdNumber)) { return { success: false, message: "Profile id must be a number" }; }
        const profile = user.profiles.find(p => p.id === profileIdNumber);
        if (!profile) { return { success: false, message: "Profile not found" }; }
        const isLiked = profile.wasLiked_Media_IDs.has(mediaIdNumber);

        if (isLiked)
        {
            profile.wasLiked_Media_IDs.delete(mediaIdNumber);
            media.likes = Math.max(0, media.likes - 1);
        }
        else
        {
            profile.wasLiked_Media_IDs.add(mediaIdNumber);
            media.likes++;
        }
        return { success: true, message: "Media like toggled successfully" , data: { profile: profile.toJSON(), media: media.toJSON() }};
    }

    /** 
     * @param {string} userId 
     * @param {string} profileId 
     * @param {string} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async addMediaToWatchHistory(userId, profileId, mediaId)
    {
        const mediaIdNumber = Number(mediaId);
        if (Number.isNaN(mediaIdNumber)) { return { success: false, message: "Media id must be a number" }; }
        const media = this.media[mediaIdNumber];
        if (!media) { return { success: false, message: "Media not found" }; }
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        const profileIdNumber = Number(profileId);
        if (Number.isNaN(profileIdNumber)) { return { success: false, message: "Profile id must be a number" }; }
        const profile = user.profiles.find(p => p.id === profileIdNumber);
        if (!profile) { return { success: false, message: "Profile not found" }; }
        if (profile.LastWatched_Media_IDs.includes(mediaIdNumber))
        {
            profile.LastWatched_Media_IDs = profile.LastWatched_Media_IDs.filter(id => id !== mediaIdNumber);
        }
        profile.LastWatched_Media_IDs.unshift(mediaIdNumber);
        
        profile.LastWatched_Media_IDs = profile.LastWatched_Media_IDs.slice(0, Constants.MAX_LAST_WATCHED_MEDIA_LIMIT);
        
        return { success: true, message: "Media added to watch history successfully" , data: { profile: profile.toJSON()}};
    }
}

module.exports = MemoryStorage;