/* eslint-disable no-unused-vars */
const { User, UserProfile, Media } = require('../entities.js');
const StorageContract = require('./storage-contract.js');
const constants = require('../constants.js');
/**
 * @typedef {Object} StorageResponse
 * @property {boolean} success - Operation status
 * @property {string} [message] - Message describing the operation result
 * @property {any} [data] - Returned data (User, Array of Media, etc.)
 */

/**
 * Abstract Base Class defining the Data Access Layer.
 */
class MemoryStorage extends StorageContract
{
    constructor()
    {
        super();
        this.users = {};//key: userId, value: User
        this.AvailableUserId = 0;
        this.AvailableMediaId = 0;
        this.email2userId = {};//key: email, value: UserId
        this.phone2userId = {};//key: phone, value: UserId
        this.media = {};//key: mediaId, value: Media

    }

    // ==========================================
    // User & Auth Management
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllUsers()
    {
        const stringifiedUsers = Object.values(this.users).map(u => this._CloneUserToString(u));
        return { success: true, data: stringifiedUsers };
    }

    /** @param {string} userId @returns {Promise<StorageResponse>} */
    async getUserById(userId)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        if (userIdNumber < 0) { return { success: false, message: "User id must be positive" }; }
        
        const user = this.users[userIdNumber];
        if (user === undefined) { return { success: false, message: "User not found" }; }
        
        return { success: true, data: this._CloneUserToString(user) };
    }

    /** @param {string} email @returns {Promise<StorageResponse>} */
    async getUserByEmail(email) 
    { 
        const userId = this.email2userId[email];
        if (userId === undefined) { return { success: false, message: "User not found" }; }
        
        return { success: true, data: this._CloneUserToString(this.users[userId]) };
    }

    /** @param {string} phone @returns {Promise<StorageResponse>} */
    async getUserByPhone(phone) 
    { 
        const userId = this.phone2userId[phone];
        if (userId === undefined) { return { success: false, message: "User not found" }; }
        
        return { success: true, data: this._CloneUserToString(this.users[userId]) };
    }

    /** @param {User} user object instance (id need to be undefined in order to be generated by the storage layer) @returns {Promise<StorageResponse>} */
    async registerUser(user) 
    { 
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (user.id !== undefined) { return { success: false, message: "User id must be undefined in order to be generated by the storage layer" }; }
        if (this.email2userId[user.email] !== undefined) { return { success: false, message: "Email already exists" }; }
        if (this.phone2userId[user.phone] !== undefined) { return { success: false, message: "Phone already exists" }; }
        
        //prepare the user for saving in the number format of the database
        const userToSave = this._CloneUserToNumber(user);
        userToSave.id = this.AvailableUserId;
        this.AvailableUserId += 1;
        
        this.users[userToSave.id] = userToSave;
        this.email2userId[userToSave.email] = userToSave.id;
        this.phone2userId[userToSave.phone] = userToSave.id;
        
        //save the user's profiles
        for (const profile of user.profiles)
        {
            if (profile.id !== undefined)continue;//if the profile id is defined , this is not allowed because the id will be generated by the storage
            await this.addProfile(userToSave.id, profile);
        }

        return { success: true, data: this._CloneUserToString(userToSave) };
    }

    /** @param {User} user @returns {Promise<StorageResponse>} */
    async updateUser(user)
    {
        if (!(user instanceof User)) { return { success: false, message: "User is not a valid User instance" }; }
        if (user.id === undefined) { return { success: false, message: "User id must be defined" }; }
        
        const targetId = Number(user.id);
        if (Number.isNaN(targetId) || targetId < 0) { return { success: false, message: "User id must be a number and positive" }; }
        const existingUser = this.users[targetId];
        if (!existingUser) { return { success: false, message: "User not found" }; }

        if (this.email2userId[user.email] !== undefined && this.email2userId[user.email] !== targetId)
        { 
            return { success: false, message: "Email already exists" }; 
        }
        if (this.phone2userId[user.phone] !== undefined && this.phone2userId[user.phone] !== targetId)
        { 
            return { success: false, message: "Phone already exists" }; 
        }
        
        delete this.email2userId[existingUser.email];
        delete this.phone2userId[existingUser.phone];
        
        const userToSave = this._CloneUserToNumber(user);
        userToSave.id = targetId;
        
        this.users[userToSave.id] = userToSave;
        this.email2userId[userToSave.email] = userToSave.id;
        this.phone2userId[userToSave.phone] = userToSave.id;

        return { success: true, data: this._CloneUserToString(userToSave) };
    }
    // ==========================================
    // Profile Management
    // ==========================================

    /** @param {string} userId @returns {Promise<StorageResponse>} */
    async getUserProfiles(userId)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        
        const stringifiedProfiles = user.profiles.map(p => this._CloneProfileToString(p));
        return { success: true, data: stringifiedProfiles };
    }

    /** * @param {string} userId 
     * @param {UserProfile} profile - the profile to add to the storage (id need to be undefined in order to be generated by the storage layer)
     * @returns {Promise<StorageResponse>} 
     * */
    async addProfile(userId, profile)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userIdNumber];
        if (!user) { return { success: false, message: "User not found" }; }
        if (profile.id !== undefined) { return { success: false, message: "Profile id must be undefined in order to be generated by the storage layer" }; }
        
        let nextId = 0;
        for (const p of user.profiles)
        {
            if(p.id === nextId)nextId++;
        }
        if (nextId >= constants.MAX_PROFILES_PER_USER) { return { success: false, message: "Max profiles per user reached" }; }
        
        const profileToSave = this._CloneProfileToNumber(profile);
        profileToSave.id = nextId;
        
        user.profiles.push(profileToSave);
        return { success: true, data: this._CloneProfileToString(profileToSave) };
    }


    /**
     * @param {string} userId 
     * @param {Array<UserProfile>} profiles - the list of profiles to update in the storage
     * @returns {Promise<StorageResponse>} 
     * */
    async updateProfiles(userId, profiles)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) return { success: false, message: "User id must be a number" };
        const user = this.users[userIdNumber];
        if (!user) return { success: false, message: "User not found" };
        
        for (let i = 0; i < profiles.length; i++)
        {
            const response = await this.updateProfile(userId, profiles[i]);
            if (!response.success) 
            {
                return response;
            }
        }
        
        const stringifiedProfiles = user.profiles.map(p => this._CloneProfileToString(p));
        return { success: true, data: stringifiedProfiles };
    }


    /**
     * @param {string} userId 
     * @param {UserProfile} profile - the profile to update in the storage
     * @returns {Promise<StorageResponse>} 
     * */
    async updateProfile(userId, profile)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) return { success: false, message: "User id must be a number" };
        
        const user = this.users[userIdNumber];
        if (!user) return { success: false, message: "User not found" };
        
        const pId = Number(profile.id);
        if (Number.isNaN(pId) || pId < 0) return { success: false, message: "Profile id must be defined and positive" };
        
        const index = user.profiles.findIndex(p => p.id === pId);
        if (index === -1) return { success: false, message: "Profile not found" };
        
        user.profiles[index].name = profile.name !== undefined ? profile.name : user.profiles[index].name;
        user.profiles[index].imageName = profile.imageName !== undefined ? profile.imageName : user.profiles[index].imageName;        
        
        return { success: true, data: this._CloneProfileToString(user.profiles[index]) };
    }

    /**
     * @param {string} userId 
     * @param {string} profileId 
     * @returns {Promise<StorageResponse>} 
     * */
    async deleteProfile(userId, profileId)
    {
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) return { success: false, message: "User id must be a number" };
        const user = this.users[userIdNumber];
        if (!user) return { success: false, message: "User not found" };
        const profileIdNumber = Number(profileId);
        if (Number.isNaN(profileIdNumber)) return { success: false, message: "Profile id must be a number" };
        
        const profile = user.profiles.find(p => p.id === profileIdNumber);
        if (!profile) return { success: false, message: "Profile not found" };
        
        user.profiles = user.profiles.filter(p => p.id !== profileIdNumber);
        return { success: true};
    }

    // ==========================================
    // Media & Interaction
    // ==========================================

    /** @returns {Promise<StorageResponse>} */
    async getAllMedia()
    {
        const stringifiedMedia = Object.values(this.media).map(m => this._CloneMediaToString(m));
        return { success: true, data: stringifiedMedia };
    }

    /** @param {number} mediaId @returns {Promise<StorageResponse>} */
    async getMediaById(mediaId)
    {
        const mediaIdNumber = Number(mediaId);
        if (Number.isNaN(mediaIdNumber)) { return { success: false, message: "Media id must be a number" }; }
        if (mediaIdNumber < 0) { return { success: false, message: "Media id must be positive" }; }
        
        const media = this.media[mediaIdNumber];
        if (media === undefined) { return { success: false, message: "Media not found" }; }
        
        return { success: true, data: this._CloneMediaToString(media) };
    }

    /** * @param {string} userId 
     * @param {string} profileId 
     * @param {string} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async toggleMediaLike(userId, profileId, mediaId) 
    {
        const mediaIdNumber = Number(mediaId);
        if (Number.isNaN(mediaIdNumber)) { return { success: false, message: "Media id must be a number" }; }
        const media = this.media[mediaIdNumber];
        if (media === undefined) { return { success: false, message: "Media not found" }; }
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userIdNumber];
        if (user === undefined) { return { success: false, message: "User not found" }; }
        const profileIdNumber = Number(profileId);
        if (Number.isNaN(profileIdNumber)) { return { success: false, message: "Profile id must be a number" }; }
        const profile = user.profiles.find(p => p.id === profileIdNumber);
        if (profile === undefined) { return { success: false, message: "Profile not found" }; }
        
        const isLiked = profile.wasLiked_Media_IDs.has(mediaIdNumber);

        if (isLiked)
        {
            profile.wasLiked_Media_IDs.delete(mediaIdNumber);
            media.likes = Math.max(0, media.likes - 1);
        }
        else
        {
            profile.wasLiked_Media_IDs.add(mediaIdNumber);
            media.likes++;
        }
        
        return { 
            success: true, 
            message: "Media like toggled successfully", 
            data: { 
                profile: this._CloneProfileToString(profile), 
                media: this._CloneMediaToString(media) 
            }
        };
    }

    /** * @param {string} userId 
     * @param {string} profileId 
     * @param {string} mediaId 
     * @returns {Promise<StorageResponse>} 
     */
    async addMediaToWatchHistory(userId, profileId, mediaId)
    {
        const mediaIdNumber = Number(mediaId);
        if (Number.isNaN(mediaIdNumber)) { return { success: false, message: "Media id must be a number" }; }
        const media = this.media[mediaIdNumber];
        if (media === undefined) { return { success: false, message: "Media not found" }; }
        const userIdNumber = Number(userId);
        if (Number.isNaN(userIdNumber)) { return { success: false, message: "User id must be a number" }; }
        const user = this.users[userIdNumber];
        if (user === undefined) { return { success: false, message: "User not found" }; }
        const profileIdNumber = Number(profileId);
        if (Number.isNaN(profileIdNumber)) { return { success: false, message: "Profile id must be a number" }; }
        const profile = user.profiles.find(p => p.id === profileIdNumber);
        if (profile === undefined) { return { success: false, message: "Profile not found" }; }
        
        if (profile.LastWatched_Media_IDs.includes(mediaIdNumber))
        {
            profile.LastWatched_Media_IDs = profile.LastWatched_Media_IDs.filter(id => id !== mediaIdNumber);
        }
        profile.LastWatched_Media_IDs.unshift(mediaIdNumber);
        profile.LastWatched_Media_IDs = profile.LastWatched_Media_IDs.slice(0, constants.MAX_LAST_WATCHED_MEDIA_LIMIT);
        
        return { 
            success: true, 
            message: "Media added to watch history successfully", 
            data: { profile: this._CloneProfileToString(profile) }
        };
    }

    /** * @param {Media} media - the media to add to the storage (id need to be undefined in order to be generated by the storage layer)
     * @returns {Promise<StorageResponse>} */
    async addMedia(media)
    {
        if (!(media instanceof Media)) { return { success: false, message: "Media is not a valid Media instance" }; }
        if (media.id !== undefined) { return { success: false, message: "Media id must be undefined in order to be generated by the storage layer" }; }
        
        const mediaToSave = this._CloneMediaToNumber(media);
        mediaToSave.id = this.AvailableMediaId;
        
        this.media[mediaToSave.id] = mediaToSave;
        this.AvailableMediaId = mediaToSave.id + 1;
        
        return { success: true, data: this._CloneMediaToString(mediaToSave) };
    }

//---------------------------------- HELPER ---------------------------------------

    _CloneUserToNumber(user)
    {
        const clonedUser = user.clone();
        clonedUser.id = user.id !== undefined && user.id !== null ? Number(user.id) : undefined;
        clonedUser.profiles = (clonedUser.profiles || []).map(p => this._CloneProfileToNumber(p));
        return clonedUser;
    }

    _CloneUserToString(user)
    {
        const clonedUser = user.clone();
        clonedUser.id = user.id !== undefined && user.id !== null ? String(user.id) : undefined;
        clonedUser.profiles = (clonedUser.profiles || []).map(p => this._CloneProfileToString(p));
        return clonedUser;
    }

    _CloneProfileToNumber(profile)
    {
        const clonedProfile = profile.clone();
        clonedProfile.id = profile.id !== undefined && profile.id !== null ? Number(profile.id) : undefined;
        clonedProfile.LastWatched_Media_IDs = (clonedProfile.LastWatched_Media_IDs || []).map(id => Number(id));
        
        clonedProfile.wasLiked_Media_IDs = (clonedProfile.wasLiked_Media_IDs || []).map(id => Number(id));
        return clonedProfile;
    }

    _CloneProfileToString(profile)
    {
        const clonedProfile = profile.clone();
        clonedProfile.id = profile.id !== undefined && profile.id !== null ? String(profile.id) : undefined;
        clonedProfile.LastWatched_Media_IDs = (clonedProfile.LastWatched_Media_IDs || []).map(id => String(id));
        
        clonedProfile.wasLiked_Media_IDs = (clonedProfile.wasLiked_Media_IDs || []).map(id => String(id));
        return clonedProfile;
    }

    _CloneMediaToNumber(media)
    {
        const clonedMedia = media.clone();
        clonedMedia.id = media.id !== undefined && media.id !== null ? Number(media.id) : undefined;
        return clonedMedia;
    }

    _CloneMediaToString(media)
    {
        const clonedMedia = media.clone();
        clonedMedia.id = media.id !== undefined && media.id !== null ? String(media.id) : undefined;
        return clonedMedia;
    }
}

module.exports = MemoryStorage;